--ACCESS=forena category Voyager - Profiles - Acquisitions
select ap.acq_profile_name,
	  o.first_name,
	  o.last_name,
	  ao.operator_id,
	  ap.order_add_update,
	  ap.receive,
	  ap.order_delete,
	  ap.order_view_only,
	  ap.order_approve,
	  ap.serial_checkin,
	  ap.serials_view_only,
	  ap.pattern_add_update,
	  ap.pattern_view_only,
	  ap.pattern_delete,
	  ap.item_add_update,
	  ap.item_delete,
	  ap.item_view_only,
	  ap.mono_claims,
	  ap.serial_claims,
	  ap.problems_claims_view_only,
	  ap.change_line_item_bib,
	  ap.hold_ignore_ownership,
	  ap.vendor_add_update,
	  ap.vendor_delete,
	  ap.vendor_view_only,
	  ap.ledger_add_update,
	  ap.ledger_view_only,
	  ap.ledger_delete,
	  ap.change_fund_alloc,
	  ap.fiscal_close,
	  ap.currency_maintenance,
	  ap.edi_incoming,
	  ap.edi_outgoing,
	  ap.modify_edi_outgoing,
	  ap.invoice_add_update,
	  ap.invoice_view_only,
	  ap.invoice_delete,
	  ap.invoice_approve,
	  ap.bind_view_vol_issue,
	  ap.bind_edit_vol,
	  ap.bind_edit_issue,
	  ap.bind_print,
	  ap.override_expend,
	  ap.override_commit
from pittdb.acq_profile ap,
	pittdb.operator o,
	pittdb.acq_operator ao
where ap.acq_profile_id = ao.acq_profile_id
	and ao.operator_id = o.operator_id
order by ap.acq_profile_name
