--ACCESS=forena category Voyager - Profiles - Circulation
select cp.circ_profile_name,
	o.first_name,
	o.last_name,
	co.operator_id,
	cp.charge_renew,
	cp.discharge,
	cp.recahold_add_update,
	cp.item_add_update,
	cp.add_fines,
	cp.pay_fines,
	cp.patron_add_update,
	cp.update_pin,
	cp.patron_delete,
	cp.patron_proxy_maintain,
	cp.hold_ignore_ownership,
	cp.item_delete,
	cp.change_due_date,
	cp.change_discharge_date,
	cp.patron_mask_ssn,
	cp.recahold_resequence,
	cp.item_status,
	cp.forgive_fines,
	cp.reserve_add_update,
	cp.patron_view_only,
	cp.patron_counters,
	cp.edit_stub_patron,
	cp.manually_map_patron,
	cp.view_patron_circ_history,
	cp.distribution_item_view,
	cp.distribution_item_distribute,
	cp.distribution_item_create,
	cp.distribution_item_update,
	cp.distribution_item_order,
	cp.distribution_item_receive,
	cp.distribution_item_delete
from pittdb.circ_profile cp,
	pittdb.operator o,
	pittdb.circ_operator co
where cp.circ_profile_id = co.circ_profile_id
	and co.operator_id = o.operator_id
order by cp.circ_profile_name
