SELECT
	MARC_COUNTRIES.COUNTRY_CODE,
	MARC_COUNTRIES.COUNTRY_NAME,
	MARC_COUNTRIES.COUNTRY_REGION,
	COUNT(DISTINCT BIB_MASTER.BIB_ID) BIBS,
	COUNT(DISTINCT NVL(MFHD_MASTER.MFHD_ID,0)) - MAX(CASE WHEN MFHD_MASTER.MFHD_ID IS NULL THEN 1 ELSE 0 END) MFHDS,
	COUNT(DISTINCT NVL(ITEM.ITEM_ID,0)) - MAX(CASE WHEN ITEM.ITEM_ID IS NULL THEN 1 ELSE 0 END) ITEMS
FROM
	PITTDB.BIB_MASTER
	JOIN PITTDB.BIB_TEXT ON (BIB_MASTER.BIB_ID = BIB_TEXT.BIB_ID)
	--IF=:include_invalid
	LEFT OUTER 
	--END
	JOIN VOYAPPS.MARC_COUNTRIES ON (SUBSTR(BIB_TEXT.FIELD_008, 16, 3) = MARC_COUNTRIES.COUNTRY_CODE)
	LEFT OUTER JOIN PITTDB.BIB_MFHD ON (BIB_MFHD.BIB_ID = BIB_MASTER.BIB_ID)
	LEFT OUTER JOIN PITTDB.MFHD_MASTER ON (MFHD_MASTER.MFHD_ID = BIB_MFHD.MFHD_ID)
	LEFT OUTER JOIN PITTDB.MFHD_ITEM ON (MFHD_ITEM.MFHD_ID = BIB_MFHD.MFHD_ID)
	LEFT OUTER JOIN PITTDB.ITEM ON (ITEM.ITEM_ID = MFHD_ITEM.ITEM_ID)
WHERE
	BIB_MASTER.SUPPRESS_IN_OPAC = 'N'
	AND NVL(MFHD_MASTER.SUPPRESS_IN_OPAC, 'N') = 'N'
	AND (
		ITEM.ITEM_ID IS NULL OR
		ITEM.ITEM_ID NOT IN (SELECT ITEM_STATUS.ITEM_ID FROM PITTDB.ITEM_STATUS WHERE ITEM_STATUS.ITEM_STATUS BETWEEN 12 AND 17 AND ITEM_STATUS.ITEM_ID = ITEM.ITEM_ID)
	)
	AND (
		--IF=:include_invalid
		(:include_invalid = '1' AND MARC_COUNTRIES.COUNTRY_CODE IS NULL) OR
		--END
		MARC_COUNTRIES.COUNTRY_CODE IN :marc_countries
	)
GROUP BY
	MARC_COUNTRIES.COUNTRY_CODE,
	MARC_COUNTRIES.COUNTRY_NAME,
	MARC_COUNTRIES.COUNTRY_REGION
ORDER BY
	MARC_COUNTRIES.COUNTRY_REGION,
	MARC_COUNTRIES.COUNTRY_NAME
--INFO
type[marc_countries]=array

