--ACCESS=access content
SELECT
      ALLRANGES.RANGENO,
      ALLSHELVES.SHELFNO,
      S1.NUMTRAYS || '/' || S1.TRAYSIZE M1,
      S2.NUMTRAYS || '/' || S2.TRAYSIZE M2,
      S3.NUMTRAYS || '/' || S3.TRAYSIZE M3,
      S4.NUMTRAYS || '/' || S4.TRAYSIZE M4,
      S5.NUMTRAYS || '/' || S5.TRAYSIZE M5,
      S6.NUMTRAYS || '/' || S6.TRAYSIZE M6,
      S7.NUMTRAYS || '/' || S7.TRAYSIZE M7,
      S8.NUMTRAYS || '/' || S8.TRAYSIZE M8,
      S9.NUMTRAYS || '/' || S9.TRAYSIZE M9,
      S10.NUMTRAYS || '/' || S10.TRAYSIZE M10,
      S11.NUMTRAYS || '/' || S11.TRAYSIZE M11,
      S12.NUMTRAYS || '/' || S12.TRAYSIZE M12,
      S13.NUMTRAYS || '/' || S13.TRAYSIZE M13,
      S14.NUMTRAYS || '/' || S14.TRAYSIZE M14,
      S15.NUMTRAYS || '/' || S15.TRAYSIZE M15,
      S16.NUMTRAYS || '/' || S16.TRAYSIZE M16,
      S17.NUMTRAYS || '/' || S17.TRAYSIZE M17,
      S18.NUMTRAYS || '/' || S18.TRAYSIZE M18,
      S19.NUMTRAYS || '/' || S19.TRAYSIZE M19,
      S20.NUMTRAYS || '/' || S20.TRAYSIZE M20,
      S21.NUMTRAYS || '/' || S21.TRAYSIZE M21,
      S22.NUMTRAYS || '/' || S22.TRAYSIZE M22,
      S23.NUMTRAYS || '/' || S23.TRAYSIZE M23,
      S24.NUMTRAYS || '/' || S24.TRAYSIZE M24
FROM
      (
            SELECT
                  DISTINCT RANGENO
            FROM
                  VOYAPPS.HDSSHELF
      ) ALLRANGES
      CROSS JOIN (
            SELECT
                  DISTINCT SHELFNO
            FROM
                  VOYAPPS.HDSSHELF
      ) ALLSHELVES
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S1 ON (S1.RANGENO = ALLRANGES.RANGENO AND S1.SHELFNO = ALLSHELVES.SHELFNO AND S1.MODULENO = 1)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S2 ON (S2.RANGENO = ALLRANGES.RANGENO AND S2.SHELFNO = ALLSHELVES.SHELFNO AND S2.MODULENO = 2)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S3 ON (S3.RANGENO = ALLRANGES.RANGENO AND S3.SHELFNO = ALLSHELVES.SHELFNO AND S3.MODULENO = 3)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S4 ON (S4.RANGENO = ALLRANGES.RANGENO AND S4.SHELFNO = ALLSHELVES.SHELFNO AND S4.MODULENO = 4)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S5 ON (S5.RANGENO = ALLRANGES.RANGENO AND S5.SHELFNO = ALLSHELVES.SHELFNO AND S5.MODULENO = 5)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S6 ON (S6.RANGENO = ALLRANGES.RANGENO AND S6.SHELFNO = ALLSHELVES.SHELFNO AND S6.MODULENO = 6)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S7 ON (S7.RANGENO = ALLRANGES.RANGENO AND S7.SHELFNO = ALLSHELVES.SHELFNO AND S7.MODULENO = 7)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S8 ON (S8.RANGENO = ALLRANGES.RANGENO AND S8.SHELFNO = ALLSHELVES.SHELFNO AND S8.MODULENO = 8)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S9 ON (S9.RANGENO = ALLRANGES.RANGENO AND S9.SHELFNO = ALLSHELVES.SHELFNO AND S9.MODULENO = 9)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S10 ON (S10.RANGENO = ALLRANGES.RANGENO AND S10.SHELFNO = ALLSHELVES.SHELFNO AND S10.MODULENO = 10)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S11 ON (S11.RANGENO = ALLRANGES.RANGENO AND S11.SHELFNO = ALLSHELVES.SHELFNO AND S11.MODULENO = 11)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S12 ON (S12.RANGENO = ALLRANGES.RANGENO AND S12.SHELFNO = ALLSHELVES.SHELFNO AND S12.MODULENO = 12)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S13 ON (S13.RANGENO = ALLRANGES.RANGENO AND S13.SHELFNO = ALLSHELVES.SHELFNO AND S13.MODULENO = 13)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S14 ON (S14.RANGENO = ALLRANGES.RANGENO AND S14.SHELFNO = ALLSHELVES.SHELFNO AND S14.MODULENO = 14)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S15 ON (S15.RANGENO = ALLRANGES.RANGENO AND S15.SHELFNO = ALLSHELVES.SHELFNO AND S15.MODULENO = 15)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S16 ON (S16.RANGENO = ALLRANGES.RANGENO AND S16.SHELFNO = ALLSHELVES.SHELFNO AND S16.MODULENO = 16)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S17 ON (S17.RANGENO = ALLRANGES.RANGENO AND S17.SHELFNO = ALLSHELVES.SHELFNO AND S17.MODULENO = 17)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S18 ON (S18.RANGENO = ALLRANGES.RANGENO AND S18.SHELFNO = ALLSHELVES.SHELFNO AND S18.MODULENO = 18)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S19 ON (S19.RANGENO = ALLRANGES.RANGENO AND S19.SHELFNO = ALLSHELVES.SHELFNO AND S19.MODULENO = 19)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S20 ON (S20.RANGENO = ALLRANGES.RANGENO AND S20.SHELFNO = ALLSHELVES.SHELFNO AND S20.MODULENO = 20)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S21 ON (S21.RANGENO = ALLRANGES.RANGENO AND S21.SHELFNO = ALLSHELVES.SHELFNO AND S21.MODULENO = 21)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S22 ON (S22.RANGENO = ALLRANGES.RANGENO AND S22.SHELFNO = ALLSHELVES.SHELFNO AND S22.MODULENO = 22)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S23 ON (S23.RANGENO = ALLRANGES.RANGENO AND S23.SHELFNO = ALLSHELVES.SHELFNO AND S23.MODULENO = 23)
      LEFT OUTER JOIN VOYAPPS.HDSSHELF S24 ON (S24.RANGENO = ALLRANGES.RANGENO AND S24.SHELFNO = ALLSHELVES.SHELFNO AND S24.MODULENO = 24)
ORDER BY
      ALLRANGES.RANGENO,
      ALLSHELVES.SHELFNO DESC

