--ACCESS=access content
SELECT
	RECORD_SET_RECORDS.RECORD_ID,
	RECORD_TYPE.RECORD_TYPE_DESC
FROM
	RECORD_SET_RECORDS
	JOIN RECORD_SET ON (RECORD_SET_RECORDS.RECORD_SET_ID = RECORD_SET.RECORD_SET_ID)
	JOIN RECORD_TYPE ON (RECORD_SET.RECORD_TYPE_ID = RECORD_TYPE.RECORD_TYPE_ID)
WHERE
	RECORD_SET.RECORD_SET_ID = :recordsetid
