SELECT
	BIB_MFHD.BIB_ID,
	BIB_MASTER.SUPPRESS_IN_OPAC BIB_SUPPRESSED,
	BIB_MFHD.MFHD_ID,
	MFHD_MASTER.SUPPRESS_IN_OPAC MFHD_SUPPRESSED,
	MFHD_ITEM.ITEM_ID,
	(SELECT v.item_status_desc FROM (SELECT t.item_status_desc, s.item_id FROM item_status_type t JOIN item_status s ON (t.item_status_type = s.item_status) ORDER BY s.item_status_date DESC) v where v.item_id = ITEM_BARCODE.ITEM_ID and ROWNUM = 1) LAST_ITEM_STATUS,
	ITEM_BARCODE.ITEM_BARCODE,
	ITEM_BARCODE.BARCODE_STATUS,
	MFHD_LOCATION.LOCATION_CODE MFHD_LOCATION,
	ITEM_LOCATION.LOCATION_CODE ITEM_LOCATION
FROM
	RECORD_SET_RECORDS
	JOIN RECORD_SET ON (RECORD_SET_RECORDS.RECORD_SET_ID = RECORD_SET.RECORD_SET_ID)
	JOIN RECORD_TYPE ON (RECORD_SET.RECORD_TYPE_ID = RECORD_TYPE.RECORD_TYPE_ID)
	JOIN BIB_MFHD ON ((RECORD_TYPE.RECORD_TYPE_DESC = 'BIB_RECORD' AND RECORD_SET_RECORDS.RECORD_ID = BIB_MFHD.BIB_ID) OR (RECORD_TYPE.RECORD_TYPE_DESC='MFHD_RECORD' AND RECORD_SET_RECORDS.RECORD_ID = BIB_MFHD.MFHD_ID))
	JOIN BIB_MASTER ON (BIB_MFHD.BIB_ID = BIB_MASTER.BIB_ID)
	JOIN MFHD_MASTER ON (BIB_MFHD.MFHD_ID = MFHD_MASTER.MFHD_ID)
	LEFT OUTER JOIN MFHD_ITEM ON (BIB_MFHD.MFHD_ID = MFHD_ITEM.MFHD_ID)
	LEFT OUTER JOIN ITEM_BARCODE ON (MFHD_ITEM.ITEM_ID = ITEM_BARCODE.ITEM_ID)
	LEFT OUTER JOIN ITEM ON (MFHD_ITEM.ITEM_ID = ITEM.ITEM_ID)
	JOIN LOCATION MFHD_LOCATION ON (MFHD_LOCATION.LOCATION_ID = MFHD_MASTER.LOCATION_ID)
	LEFT OUTER JOIN LOCATION ITEM_LOCATION ON (ITEM_LOCATION.LOCATION_ID = ITEM.PERM_LOCATION)
WHERE
	RECORD_SET.RECORD_SET_ID = :recordsetid
