--ACCESS=forena category ACRL
SELECT 'Media (Physical)' category, COUNT(*) title_count
FROM BIB_MASTER JOIN BIB_TEXT USING (BIB_ID)
WHERE BIB_MASTER.SUPPRESS_IN_OPAC != 'Y' AND 
BIB_ID IN (SELECT BIB_MEDIUM.BIB_ID FROM BIB_MEDIUM WHERE BIB_MEDIUM.MEDIUM IN ('g', 'h', 'm', 's', 'v')) AND
BIB_ID NOT IN (SELECT BIB_MEDIUM.BIB_ID FROM BIB_MEDIUM WHERE BIB_MEDIUM.MEDIUM = 'c')
UNION
SELECT 'Media (Digital)' category, COUNT(*) title_count
FROM BIB_MASTER JOIN BIB_TEXT USING (BIB_ID)
WHERE BIB_MASTER.SUPPRESS_IN_OPAC != 'Y' AND 
BIB_ID IN (SELECT BIB_MEDIUM.BIB_ID FROM BIB_MEDIUM WHERE BIB_MEDIUM.MEDIUM IN ('g', 'h', 'm', 's', 'v')) AND
BIB_ID IN (SELECT BIB_MEDIUM.BIB_ID FROM BIB_MEDIUM WHERE BIB_MEDIUM.MEDIUM = 'c')
UNION
SELECT 'Serials (Digital)' category, COUNT(*) title_count
FROM BIB_MASTER JOIN BIB_TEXT USING (BIB_ID)
WHERE BIB_MASTER.SUPPRESS_IN_OPAC != 'Y' AND BIB_TEXT.BIB_FORMAT LIKE '%s' AND
SUBSTR(BIB_TEXT.FIELD_008, 24, 1) IN ('q', 'o', 's')
UNION
SELECT 'Serials (Physical)' category, COUNT(*) title_count
FROM BIB_MASTER JOIN BIB_TEXT USING (BIB_ID)
WHERE BIB_MASTER.SUPPRESS_IN_OPAC != 'Y' AND BIB_TEXT.BIB_FORMAT LIKE '%s' AND
SUBSTR(BIB_TEXT.FIELD_008, 24, 1) NOT IN ('q', 'o', 's')
