SELECT
 CALL_SLIPS.CALL_SLIP_ID,
 CALL_SLIPS.DATE_PROCESSED,
 BIB_TEXT.TITLE_BRIEF,
 MFHD_ITEM.ITEM_ENUM,
 MFHD_ITEM.CHRON,
 PATRON_GROUP.PATRON_GROUP_NAME,
 NO_FILL_REASON.REASON_CODE,
 CALL_SLIP_STATUS_TYPE.STATUS_DESC
FROM 
 (
  SELECT CALL_SLIP_ID, BIB_ID, PATRON_GROUP_ID, NO_FILL_REASON, STATUS, ITEM_ID, MFHD_ID, LOCATION_ID, DATE_PROCESSED FROM CALL_SLIP
  UNION
  SELECT ARCHIVE_ID, BIB_ID, PATRON_GROUP_ID, NO_FILL_REASON, STATUS, ITEM_ID, MFHD_ID, LOCATION_ID, DATE_PROCESSED FROM CALL_SLIP_ARCHIVE
 ) CALL_SLIPS JOIN
 PATRON_GROUP ON (CALL_SLIPS.PATRON_GROUP_ID = PATRON_GROUP.PATRON_GROUP_ID) JOIN
 BIB_TEXT ON (CALL_SLIPS.BIB_ID = BIB_TEXT.BIB_ID) LEFT OUTER JOIN
 NO_FILL_REASON ON (CALL_SLIPS.NO_FILL_REASON = NO_FILL_REASON.REASON_ID) JOIN
 CALL_SLIP_STATUS_TYPE ON (CALL_SLIPS.STATUS = CALL_SLIP_STATUS_TYPE.STATUS_TYPE) LEFT OUTER JOIN
 MFHD_ITEM ON (MFHD_ITEM.MFHD_ID = CALL_SLIPS.MFHD_ID AND MFHD_ITEM.ITEM_ID = CALL_SLIPS.ITEM_ID)
WHERE
 BIB_TEXT.BIB_FORMAT LIKE '_s' AND
 LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATION WHERE LOCATION_CODE IN ('tbper', 'tbpernew')) AND
 CALL_SLIPS.DATE_PROCESSED BETWEEN TO_DATE(:begin_date, 'YYYY-MM-DD') AND TO_DATE(:end_date, 'YYYY-MM-DD') + 1 AND
 (NO_FILL_REASON.REASON_CODE IS NULL OR NO_FILL_REASON.REASON_CODE IN ('J-LINK','J-INCOMPL','J-ONLINE','J-NOTFND'))
ORDER BY
 CALL_SLIPS.DATE_PROCESSED
