SELECT
      CALL_SLIPS.CALL_SLIP_ID,
      CASE
            WHEN NO_FILL_REASON.REASON_CODE = 'J-LINK' THEN 'Filled J-LINK'
            ELSE CALL_SLIP_STATUS_TYPE.STATUS_DESC
      END STATUS,
      CALL_SLIPS.DATE_REQUESTED,
      CALL_SLIPS.DATE_PROCESSED,
      HOLD_RECALLS.CREATE_DATE,
      HOLD_RECALLS.AVAILABLE_NOTICE_DATE,
      CALL_SLIP_PICKUP_LOCATION.LOCATION_CODE CALL_SLIP_PICKUP,
      HOLD_PICKUP_LOCATION.LOCATION_CODE
FROM
      (
            SELECT
                  CALL_SLIP.CALL_SLIP_ID,
                  CALL_SLIP.BIB_ID,
                  CALL_SLIP.MFHD_ID,
                  CALL_SLIP.ITEM_ID,
                  CALL_SLIP.DATE_REQUESTED,
                  CALL_SLIP.DATE_PROCESSED,
                  CALL_SLIP.STATUS,
                  CALL_SLIP.PICKUP_LOCATION_ID,
                  CALL_SLIP.PRINT_GROUP_ID,
                  CALL_SLIP.NO_FILL_REASON
            FROM
                  CALL_SLIP
            UNION
            SELECT
                  CALL_SLIP.ARCHIVE_ID CALL_SLIP_ID,
                  CALL_SLIP.BIB_ID,
                  CALL_SLIP.MFHD_ID,
                  CALL_SLIP.ITEM_ID,
                  CALL_SLIP.DATE_REQUESTED,
                  CALL_SLIP.DATE_PROCESSED,
                  CALL_SLIP.STATUS,
                  CALL_SLIP.PICKUP_LOCATION_ID,
                  CALL_SLIP.PRINT_GROUP_ID,
                  CALL_SLIP.NO_FILL_REASON
            FROM
                  CALL_SLIP_ARCHIVE CALL_SLIP
      ) CALL_SLIPS
      LEFT OUTER JOIN
      (
            SELECT
                  HOLD_RECALL.CALL_SLIP_ID,
                  HOLD_RECALL.CREATE_DATE,
                  HOLD_RECALL.AVAILABLE_NOTICE_DATE,
                  HOLD_RECALL.PICKUP_LOCATION
            FROM
                  HOLD_RECALL
            UNION
            SELECT
                  HOLD_RECALL.CALL_SLIP_ID,
                  HOLD_RECALL.CREATE_DATE,
                  HOLD_RECALL.AVAILABLE_NOTICE_DATE,
                  HOLD_RECALL.PICKUP_LOCATION
            FROM
                  HOLD_RECALL_ARCHIVE HOLD_RECALL
      ) HOLD_RECALLS ON (CALL_SLIPS.CALL_SLIP_ID = HOLD_RECALLS.CALL_SLIP_ID)
      LEFT OUTER JOIN CALL_SLIP_STATUS_TYPE ON (CALL_SLIPS.STATUS = CALL_SLIP_STATUS_TYPE.STATUS_TYPE)
      LEFT OUTER JOIN NO_FILL_REASON ON (CALL_SLIPS.NO_FILL_REASON = NO_FILL_REASON.REASON_ID)
      LEFT OUTER JOIN LOCATION CALL_SLIP_PICKUP_LOCATION ON (CALL_SLIPS.PICKUP_LOCATION_ID = CALL_SLIP_PICKUP_LOCATION.LOCATION_ID)
      LEFT OUTER JOIN LOCATION HOLD_PICKUP_LOCATION ON (HOLD_RECALLS.PICKUP_LOCATION = HOLD_PICKUP_LOCATION.LOCATION_ID)
WHERE
      CALL_SLIPS.PRINT_GROUP_ID = 20
      AND CALL_SLIPS.DATE_REQUESTED BETWEEN :begin_date AND :end_date

