--ACCESS=access content
SELECT
	RECORD_SET_ID,
	CONCAT(CONCAT(RECORD_SET_NAME, ' - '), CREATE_OPERATOR_ID) RECORD_SET_NAME
FROM
	RECORD_SET
ORDER BY
	CASE WHEN LOWER(:current_user) =  LOWER(CREATE_OPERATOR_ID) THEN 2 WHEN LOWER(:current_user) = LOWER(MODIFY_OPERATOR_ID) THEN 1 ELSE 0 END DESC,
	RECORD_SET_NAME
