SELECT 'NONE' CODE, 'N/A' TEXT FROM DUAL
UNION
SELECT 'LT' CODE, 'Less-than' TEXT FROM DUAL
UNION
SELECT 'LTE' CODE, 'Less-than or Equal-to' TEXT FROM DUAL
UNION
SELECT 'GT' CODE, 'Greater-than' TEXT FROM DUAL
UNION
SELECT 'GTE' CODE, 'Greater-than or Equal-to' TEXT FROM DUAL
UNION
SELECT 'MISSING' CODE, 'Missing' TEXT FROM DUAL
